version: "3.8"
services:
  nginx:
    build:
      context: .
      dockerfile: "./dockerfiles/nginx.dockerfile"
    depends_on:
      - app
    ports:
      - "443:443"

  app:
    build:
      context: .
      dockerfile: "./dockerfiles/app-dev.dockerfile"
    volumes:
      - ".:/app"
